/**
* OOPSBannerApp UC8 – Banner Display Application
*
* This class demonstrates the creation of a visual banner displaying the word "OOPS"
* using ASCII art composed of asterisks (*) and spaces. The banner is printed to the
* console using individual print statements for each line, creating a decorativ
* text effect.
*
* We are using map collection to accomplish this
*
* The banner is generated by printing predefined string patterns line by line
* where each line contributes to forming the letters O, O, P, and S in a stylized format.
* This extends a basic user story by adding visual presentation to a simple message output.
*
* @author Developer
* @version 8
*/

import java.util.HashMap;
public class OOPSBannerApp {
	// method to create a HashMap
	public static HashMap<Character, String[]> createCharMap() {
		HashMap<Character, String[]> map = new HashMap<>();
		map.put('O', new String[] {
			"  ***  ",
			"**   **",
			"**   **",
			"**   **",
			"**   **",
			"**   **",
			"  ***  "
		});
		map.put('P', new String[] {
			"*****  ",
			"**   **",
			"**   **",
			"*****  ",
			"**     ",
			"**     ",
			"**     "
		});
		map.put('S', new String[] {
			"*******",
			"**     ",
			"**     ",
			"*******",
			"     **",
			"     **",
			"*******"

		});
		return map;
	}
	
	//method to display the banner
	public static void displayMap(String text, HashMap<Character, String[]> map) {
		int height = map.get('O').length;
		int size = text.length();
		for (int i=0;i<height;i++) {
			for (int j=0;j<size;j++) {
				char c = text.charAt(j);
				String[] pat = map.get(c);
				if (pat!=null)
					System.out.print(pat[i]+" ");
			}
			System.out.println();
		}
	}
	
	//main method
    public static void main(String[] args) {
        HashMap<Character, String[]> map = createCharMap();
        String text = "OOPS";
        displayMap(text, map);
    }
}