/**
 * OOPSBannerApp UC3 – Banner Display Application using String Join
 *
 * This class extends the fucntionality of UC2 by improving the way the "OOPS" banner
 * is constructed and displayed. It focuses on enhancing code readability and efficiency
 * by utilising the string.join() method to create line for each banner. This approach overcomes 
 * the drawbacks of using the + operator for string concatenation which can lead to 
 * code inefficieny due to creation of multiple intermediate string objects in memory.
 *
 * <p>The banner is generated by printing predefined string patterns line by line,
 * where each line contributes to forming the letters O, O, P, and S in a stylized format.
 * This extends a basic user story by adding visual presentation to a simple message output.
 * </p>
 *
 * @author Developer
 * @version 3.0
 */

public class OOPSBanner2 {

    public static void main(String[] args) {
        // Main method to run banner display
        // String.join will combine them with spaces in between
		// Each line will correspond to a row in the banner for the letters O, O, P, S.

        System.out.println(String.join(" ", "  ***  ", "  ***  ", "****  ", "******"));
        System.out.println(String.join(" ", "**   **", "**   **", "**  **", "**    "));
        System.out.println(String.join(" ", "**   **", "**   **", "**  **", "**    "));
        System.out.println(String.join(" ", "**   **", "**   **", "**  **", "******"));
        System.out.println(String.join(" ", "**   **", "**   **", "****  ", "    **"));
        System.out.println(String.join(" ", "**   **", "**   **", "**    ", "    **"));
        System.out.println(String.join(" ", "  ***  ", "  ***  ", "**    ", "******"));
    }
}

