/**
 * OOPSBannerApp UC2 – Banner Display Application
 *
 * This class demonstrates the creation of a visual banner displaying the word "OOPS"
 * using ASCII art composed of asterisks (*) and spaces. The banner is printed to the
 * console using individual print statements for each line, creating a decorative
 * text effect.
 *
 * <p>The banner is generated by printing predefined string patterns line by line,
 * where each line contributes to forming the letters O, O, P, and S in a stylized format.
 * This extends a basic user story by adding visual presentation to a simple message output.
 * </p>
 *
 * @author Developer
 * @version 2
 */

public class OOPSBannerApp {

    // Main method to run the banner display
    public static void main(String[] args) {
        // Print each line of the OOPS banner to create the visual effect
        // Each line corresponds to a row in the banner for the letters O, O, P, S

        System.out.println("  ***  " + " " + "  ***  " + " " + "****  " + " " + "******");
        System.out.println("**   **" + " " + "**   **" + " " + "**  **" + " " + "**    ");
        System.out.println("**   **" + " " + "**   **" + " " + "**  **" + " " + "**    ");
		System.out.println("**   **" + " " + "**   **" + " " + "**  **" + " " + "******");
        System.out.println("**   **" + " " + "**   **" + " " + "****  " + " " + "    **");
        System.out.println("**   **" + " " + "**   **" + " " + "**    " + " " + "    **");
        System.out.println("  ***  " + " " + "  ***  " + " " + "**    " + " " + "******");
    }
}
